### ISSUE TITLE
Can explain the flow ?

### ISSUE THREAD

**Issue by sivaprabug** [sandeep1995/angular-4-search-devs#1]
Hi @sandeep1995 ,

This is not an issue, just explain how to architect an app and code flow and what are concepts you covered. Thanks in Advanced :+1: 

regards,
@gsivaprabu

**Comment by sandeep1995** [comment]
Hi @gsivaprabu,

I do not know whether you go through my tutorial building this application using angular 4. I have explained most of the things there. If you need more explanation, I would love to help you out.
For further questions, you can comment on the blog post in the below-mentioned link.
 
[Angular 4 Tutorial](https://applyhead.com/angular-4-tutorial-make-angular-4-app-using-github-api/)

**Comment by sivaprabug** [comment]
HI @sandeep1995 ,

Thanks i got it
